name: flutter_clean_architecture_template
description: "A production-grade Flutter template using Clean Architecture principles with Riverpod state management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

dependencies:
  # Dependencies sorted alphabetically (including SDK dependencies)
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0+8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  uuid: ^4.5.1

dev_dependencies:
  # Dev dependencies sorted alphabetically (including SDK dependencies)
  build_runner: ^2.4.13
  dependency_validator: ^3.2.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.2
  riverpod_generator: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
