// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbaHKjgtESChxCtNm_rdYdnPrTW_QdZtQ',
    appId: '1:5186223346:web:6f6c4b0468a2259e6f646b',
    messagingSenderId: '5186223346',
    projectId: 'fluttertemplate-74068-dev',
    authDomain: 'fluttertemplate-74068-dev.firebaseapp.com',
    storageBucket: 'fluttertemplate-74068-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbaHKjgtESChxCtNm_rdYdnPrTW_QdZtQ',
    appId: '1:5186223346:android:6f6c4b0468a2259e6f646b',
    messagingSenderId: '5186223346',
    projectId: 'fluttertemplate-74068-dev',
    storageBucket: 'fluttertemplate-74068-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbaHKjgtESChxCtNm_rdYdnPrTW_QdZtQ',
    appId: '1:5186223346:ios:6f6c4b0468a2259e6f646c',
    messagingSenderId: '5186223346',
    projectId: 'fluttertemplate-74068-dev',
    storageBucket: 'fluttertemplate-74068-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbaHKjgtESChxCtNm_rdYdnPrTW_QdZtQ',
    appId: '1:5186223346:macos:6f6c4b0468a2259e6f646c',
    messagingSenderId: '5186223346',
    projectId: 'fluttertemplate-74068-dev',
    storageBucket: 'fluttertemplate-74068-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbaHKjgtESChxCtNm_rdYdnPrTW_QdZtQ',
    appId: '1:5186223346:windows:6f6c4b0468a2259e6f646c',
    messagingSenderId: '5186223346',
    projectId: 'fluttertemplate-74068-dev',
    storageBucket: 'fluttertemplate-74068-dev.firebasestorage.app',
  );
}
